Dev
OutSystems/cordova-plugin-fingerprint pull request #4
Opened 2019-06-11 19:55 UTC by BrunoJAzevedo

Added checkBiometry method.

Some of the changes are related to version 2.0.1

2019-06-11 20:51 UTC, Chuckytuh requested changes

2019-06-11 20:51 UTC, Chuckytuh commented on plugin.xml
> +    <dependency id="cordova-plugin-android-fingerprint-auth" url="https://github.com/OutSystems/cordova-plugin-android-fingerprint-auth.git#1.4.4" />
this dependency version does not match the version defined on [package.json](https://github.com/BrunoJAzevedo/cordova-plugin-fingerprint/blob/dev/package.json#L10-L11)

2019-06-11 20:51 UTC, Chuckytuh commented on package.json
> +    "cordova-plugin-android-fingerprint-auth":"https://github.com/OutSystems/cordova-plugin-android-fingerprint-auth.git#0.3.0-OS",
I'm not sure if plugin dependencies are to be defined on package.json or not, can't recall an instance where I've seen this happening, usually they are defined on plugin.xml alone 🤔

2019-07-23 10:52 UTC, Chuckytuh requested changes

2019-07-23 10:52 UTC, Chuckytuh commented on www/FingerPrint.js
> +			errorCallback(-1);
Don't want to nitpick but this is missing style consistency. on line 67 the function is a one-liner, in line 69 it's a multi-line function and the body is not formatted.

2019-08-26 16:20 UTC, Chuckytuh approved these changes

2019-08-26 16:30 UTC, luissilvaos approved these changes

2019-08-27 10:07 UTC, EiyuuZack commented
Hey @BrunoJAzevedo, could you please change the target of this PR to `OutSystems:master` please?

2019-08-27 14:56 UTC, BrunoJAzevedo commented
Hey @EiyuuZack that is done :)

2019-08-28 12:40 UTC, EiyuuZack requested changes
Small typo

2019-08-28 12:40 UTC, EiyuuZack commented on www/FingerPrint.js
> +    // if the device is android call th FingerprintAuth plugin
Typo

2019-08-29 15:32 UTC, BrunoJAzevedo commented on www/FingerPrint.js
> +    // if the device is android call th FingerprintAuth plugin
Fixed

2019-09-03 07:13 UTC, EiyuuZack approved these changes

2019-09-03 07:14 UTC, merged